version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: wasmtime
  - dependency-name: wasmtime-wasi
  - dependency-name: wasi-common
  - dependency-name: cap-std
  - dependency-name: wasmtime-wasi-threads