version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  ignore:
  - dependency-name: wasmtime
    versions:
    - "12.0.1"
  - dependency-name: wasmtime-wasi
    versions:
    - "12.0.1"
  - dependency-name: wasi-common
    versions:
    - "12.0.1"